vich_uploader:
    db_driver: orm

    mappings:
        blogs:
            uri_prefix: /images/blogs
            upload_destination: '%kernel.project_dir%/public/images/blogs'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
